project:
  type: website
  output-dir: docs

website:
  title: "Jafet Belmont Osuna"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: talks.qmd
        text: Talks
    right:
      - icon: envelope
        href: mailto:Jafet.BelmontOsuna@glasgow.ac.uk
      - icon: mortarboard
        href: https://orcid.org/0000-0002-6879-4412
        target: _blank

format:
  html:
    theme: [flatly, custom.scss]
    css: styles.css
    toc: false
